    name: Moodle Local Message Plugin Release

    on: workflow_dispatch

    jobs:
      build_and_release:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Package plugin
            run: |
              zip -r plugin.zip .
            # Add other steps as needed, such as running tests or uploading the package
