    name: Moodle Local Message Plugin Release

    on: workflow_dispatch

    jobs:
      build_and_release:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Package plugin
            run: |
              zip -r out/plugin.zip .
            # Add other steps as needed, such as running tests or uploading the package
          - name: Sync files
            uses: SamKirkland/FTP-Deploy-Action@v4.3.5
            with:
              server: ftp.jppaf.in
              username: u948043933.plugins
              password: ${{ secrets.ftp_password }}
              local-dir: ./out
              server-dir: ./plugin1
